# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set working directory inside container
WORKDIR /app

# Copy the JAR file from the target folder to container
COPY target/spring-boot-starter-kit-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080 for the container
EXPOSE 8080

# Run the JAR
ENTRYPOINT ["java", "-jar", "app.jar"]
