server:
  port: 8080

spring:
  application:
    name: spring-boot-starter-kit

  datasource:
    url: jdbc:postgresql://localhost:5432/starterkit
    username: postgres
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
  jwt:
  secret: **********
  access-token-expiration: 900000      # 15 mins
  refresh-token-expiration: 604800000  # 7 days
